# Generated by Django 4.2.1 on 2023-10-29 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="balance",
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
